create or replace TABLE MY_FLOW.PUBLIC.VIP_KAM_ASSIGNMENT (
	VIP_ID NUMBER(38,0),
	KAM_ID NUMBER(38,0),
	KAM_NAME VARCHAR(16777216),
	ASSIGNED_DATE TIMESTAMP_NTZ(9),
	IS_ACTIVE BOOLEAN,
	CREATED_DATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);